lesson-5: done
Stokwel/otus-ts-calc pull request #2
Opened 2021-02-22 15:56 UTC by Stokwel

Сделано почти всё:

- [x] Конфигурации JSX/TSX, за настройку storybook knobs (в последней версии storybook не требуется)
- [x] Компоненты с логикой и вложеные компоненты
- [x] Storybook для всех компонентов
- [x] Обработчки событий выводящий в консоль номер позиции клетки
- [x] Тесты loki
- [ ] Тесты на компоненты, не понял как их сделать(

2021-02-26 12:13 UTC, AntiHero requested changes

2021-02-26 12:13 UTC, AntiHero commented on .babelrc
> +    "@babel/preset-typescript",
а зачем два раза указывать preset-typescript?

2021-02-26 12:13 UTC, AntiHero commented on .storybook/main.js
> +    "@storybook/addon-links",
а storybook knobs? забыли? https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/using-addons/

2021-02-26 12:13 UTC, AntiHero commented on webpack.config.js
> +const path = require('path');
разное форматирование у файлов, в одних отступы в два пробела, в других по четыре?

2021-02-26 12:13 UTC, AntiHero commented on src/component/Cell.tsx
> +const BaseStyle = css`
а почему с большой буквы? по сути это имя класса ([аттрибута](https://www.w3schools.com/html/html_classes.asp)) какого-то компонента (тэга), да, их можно писать с большой буквы, но обычно всё же пишут с маленькой и дабы не путать их с компонентами в том числе, имена, которых тоже начинаются с большой есть смысл писать их с маленькой, вот в случае ниже, например, 
```
export const CellWrapper = styled.button<StyleProps>`
  ${BaseStyle};
  ${({isFilled}) => (isFilled ? FilledStyle : EmptyStyle)};
`;
```
с большой буквы писать правильно, потому что это уже стилизованный компонент

2021-02-26 12:13 UTC, AntiHero commented on src/index.js
> +);
почему .js , а не .tsx?

2021-02-26 12:13 UTC, AntiHero commented on webpack.config.js
> +
меняете расширение на .ts и вместо `const path = require('path');` `import path from 'path';`

2021-02-26 12:18 UTC, AntiHero commented on src/component/Field.tsx
> +export const Field: FC<FieldProps> = ({cells, onClick}) => (
Обязательно ли нам прокидывать onClick к дочерним элементам Cell? или в самом Cell можно реализовать метод, который будет выводить тот же console.log?

2021-03-02 19:33 UTC, Stokwel commented on .storybook/main.js
> +    "@storybook/addon-links",
@AntiHero на странице аддона https://storybook.js.org/addons/@storybook/addon-knobs сказано: `Use Controls addon instead for 6.0+.`

У меня стори бук 6.1.18 и аддон `Controls` я ставлю в пакете `@storybook/addon-essentials`: https://storybook.js.org/docs/react/essentials/introduction

2021-03-02 20:01 UTC, AntiHero commented on .storybook/main.js
> +    "@storybook/addon-links",
тогда всё супер, вопрос снимается, хорошо что поправили

2021-03-02 20:32 UTC, Stokwel commented on .babelrc
> +    "@babel/preset-typescript",
@AntiHero случайно. Убрал

2021-03-02 20:33 UTC, Stokwel commented on webpack.config.js
> +const path = require('path');
@AntiHero где то я копировал из примеров, а где то писал сам. В IDE у меня настроена 4 проблема, а в примерах два. Какой оставить? Два?

2021-03-02 20:34 UTC, Stokwel commented on src/component/Cell.tsx
> +const BaseStyle = css`
@AntiHero исправил. Никакой логике в этом особой не было

2021-03-02 20:34 UTC, Stokwel commented on src/index.js
> +);
@AntiHero поменял в проекте все .js на .tsx

2021-03-02 20:34 UTC, Stokwel commented on webpack.config.js
> +
@AntiHero спасибо. Сделал

2021-03-02 20:36 UTC, Stokwel commented on src/component/Field.tsx
> +export const Field: FC<FieldProps> = ({cells, onClick}) => (
@AntiHero убрал проброс `onClick` и реализовал его в компоненте `Cell`. При запуске приложения работает как надо. Но вот в `storybook` при нажатии на ячейку, во вкладки `actions` больше нет логов которые показывали бы как работает клик

2021-03-02 21:08 UTC, AntiHero commented on webpack.config.js
> +const path = require('path');
лучше 2, это стандарт

2021-03-02 21:16 UTC, vvscode commented on webpack.config.ts
> +module.exports = {
в чем смысл этого файла?

2021-03-02 21:16 UTC, vvscode commented on webpack.config.ts
> +
что не так с форматированием? (в смысле где eslint, prettier и все такое?)

2021-03-02 21:17 UTC, vvscode commented on .gitignore
> +.env.local
и `.idea` тоже хорошо бы сюда

2021-03-02 21:19 UTC, vvscode commented on src/component/Cell.tsx
> +function onClickAction(x: number, y: number): void
все же не ясно что с форматированием - тут расстановка скобок одна, а в файле ниже - другая 

какое правило?

2021-03-02 21:19 UTC, vvscode commented on src/component/Field.tsx
> +            cells?.map((row, x) => [
а зачем `?.` ? и тот же вопрос про строки

2021-03-02 21:20 UTC, vvscode commented on src/component/Field.tsx
> +                    </Cell>
можно самозакрывающуюся форму использовать

2021-03-02 21:26 UTC, AntiHero commented on src/component/Field.tsx
> +export const Field: FC<FieldProps> = ({cells, onClick}) => (
@Stokwel всё верно, потому что он теперь не указывается в args, что Вы можете сделать -  добавить в storie для Сell в export default параметры экшн хэндлеры, которые взаимодействует с Вашим элементом, т.е.
export default {
    title: 'Cell',
    component: Cell,
    parameters: {
      actions: {
        handles: ['click'],
      },
    },
} as Meta;

 [почитать](https://storybook.js.org/docs/react/essentials/actions)

2021-03-02 21:38 UTC, vvscode commented on src/component/Field.tsx
> +export const Field: FC<FieldProps> = ({cells, onClick}) => (
давайте все же прокидывать коллбэк =) нам же по итогу не вывод в консоль нужен

2021-03-04 20:25 UTC, Stokwel commented on webpack.config.js
> +const path = require('path');
@AntiHero прогнал prettier по всем файлам

2021-03-04 20:25 UTC, Stokwel commented on webpack.config.ts
> +
@vvscode прогнал prettier по всем файлам

2021-03-04 20:25 UTC, Stokwel commented on src/component/Cell.tsx
> +function onClickAction(x: number, y: number): void
@vvscode прогнал prettier по всем файлам

2021-03-04 20:25 UTC, Stokwel commented on .gitignore
> +.env.local
@vvscode добавил

2021-03-04 20:26 UTC, Stokwel commented on src/component/Field.tsx
> +            cells?.map((row, x) => [
@vvscode да похоже не зачем, у меня явно задано что это массив массивов. Убрал

2021-03-04 20:26 UTC, Stokwel commented on src/component/Field.tsx
> +                    </Cell>
@vvscode поменял

2021-03-04 20:27 UTC, Stokwel commented on webpack.config.ts
> +module.exports = {
@vvscode перенес его с прошлого урока

2021-03-04 20:27 UTC, Stokwel commented on src/component/Field.tsx
> +export const Field: FC<FieldProps> = ({cells, onClick}) => (
@vvscode @AntiHero вернул прокидывание

2021-03-09 08:19 UTC, vvscode commented on package.json
> +    "eject": "react-scripts eject",
мы же вроде написали, что CRA мы не используем, и делаем свою конфигурацию

даже в слаке об этом сказали

2021-03-09 08:20 UTC, vvscode commented on package.json
> +  "eslintConfig": {
ну и где lint-staged? мы же разбираем инструменты, чтобы ими пользоваться, а не чтобы сдавать домашки

2021-03-09 08:55 UTC, Stokwel commented on package.json
> +    "eject": "react-scripts eject",
@vvscode в этой домашке решил уже не менять. Следующую буду делать сам.

2021-03-09 11:28 UTC, AntiHero requested changes

2021-03-09 11:28 UTC, AntiHero commented on src/stories/Cell.stories.tsx
> +  onClick: (x, y) => {
не забывайте указывать тип параметров в .ts/.tsx

2021-03-09 11:28 UTC, AntiHero commented on src/stories/Cell.stories.tsx
> +  onClick: (x, y) => {
здесь тоже

2021-03-09 11:28 UTC, AntiHero commented on src/stories/Field.stories.tsx
> +  onClick: (x, y) => {
и здесь

2021-03-09 11:28 UTC, AntiHero commented on tsconfig.json
> +    "noEmit": true
будет здорово, если попробуете поработать с `noImplicitAny: true` в compilerOptions

2021-03-09 11:28 UTC, AntiHero commented on src/component/Cell.test.tsx
> +    console.info = jest.fn();
следует помнить, что в данном случае реальная имплементация `console.info` "затирается" и если последующие тесты или тестируемый код, будут вызывать `console.info`, то вызова `console.info` c нативной имплементацией не произойдёт

2021-03-09 21:13 UTC, Stokwel commented on tsconfig.json
> +    "noEmit": true
@AntiHero так она у меня и так стоит

2021-03-09 21:13 UTC, Stokwel commented on src/stories/Field.stories.tsx
> +  onClick: (x, y) => {
@AntiHero добавил, но eslint не ругался мне на это

2021-03-09 21:13 UTC, Stokwel commented on src/stories/Cell.stories.tsx
> +  onClick: (x, y) => {
@AntiHero добавил, но eslint не ругался мне на это

2021-03-09 21:13 UTC, Stokwel commented on src/stories/Cell.stories.tsx
> +  onClick: (x, y) => {
@AntiHero добавил, но eslint не ругался мне на это

2021-03-09 21:20 UTC, vvscode commented on package.json
> +    "react-dom": "^17.0.1",
это обычные зависимости

2021-03-09 21:20 UTC, vvscode commented on package.json
> +    "react-scripts": "4.0.2",
зачем?

2021-03-09 21:20 UTC, vvscode commented on package.json
> +    "ts-loader": "^8.0.14",
зачем?

2021-03-09 21:22 UTC, vvscode commented on webpack.config.ts
> +import HtmlWebpackPlugin from "html-webpack-plugin"
давай ты все же настроишь lint-staged и все остальное

2021-03-09 21:33 UTC, Stokwel commented on webpack.config.ts
> +import HtmlWebpackPlugin from "html-webpack-plugin"
@vvscode не подскажите, в каком уроке это было, а то я не смотрю следующие уроки, пока не сдам домашку

2021-03-10 12:04 UTC, AntiHero requested changes

2021-03-10 12:04 UTC, AntiHero commented on package.json
> +    "start": "webpack serve --mode development --open --hot --config ./webpack.config.ts",
`--config ./webpack.config.ts` необязательно указывать, т.к. такой конфиг(имя/путь) используется по дефолту вебпаком + а зачем --open? что он делает? и во-вторых зачем писать --mode development если этот mode уже указан у Вас в конфиге?

2021-03-10 12:10 UTC, Stokwel commented on package.json
> +    "start": "webpack serve --mode development --open --hot --config ./webpack.config.ts",
@AntiHero --open - открывает бразуер и собарнный файл, остальное было добавлено для прозрачности

2021-03-10 13:55 UTC, vvscode commented on webpack.config.ts
> +import HtmlWebpackPlugin from "html-webpack-plugin"
в задания это добавим
обычно это делают с первой домашкой (видимо у тебя это упустили)

вообще дело твое, конечно, **если код нормально отформатирова**, у тебя не отформатирован и это бросается в глаза

eslint и prettier ты точно проходил - давай ты или сам будешь помнить про запуск форматирования, или возьмешь инструмент для этого

2021-03-12 18:54 UTC, Stokwel commented on webpack.config.ts
> +import HtmlWebpackPlugin from "html-webpack-plugin"
@vvscoe добавил на прекомит и еслинт и претир

2021-03-12 18:54 UTC, Stokwel commented on package.json
> +    "react-dom": "^17.0.1",
@vvscode перенес

2021-03-12 18:54 UTC, Stokwel commented on package.json
> +    "react-scripts": "4.0.2",
@vvscode действительно незачем, убрал

2021-03-12 18:54 UTC, Stokwel commented on package.json
> +    "ts-loader": "^8.0.14",
@vvscode действительно незачем, убрал

2021-03-12 18:54 UTC, Stokwel commented on webpack.config.ts
> +import HtmlWebpackPlugin from "html-webpack-plugin"
@vvscoe добавил на прекомит и еслинт и претир

2021-03-13 13:31 UTC, AntiHero commented on package.json
> +      "eslint --max-warnings=0 src/"
почему только src? а webpack.config **.ts** в корне?

2021-03-21 09:58 UTC, closed without merging